### ISSUE TITLE
Solid.oauthing.cn cannot access

### ISSUE THREAD

**Issue by leinue** [mikeadams1/Solid-Search-App-http-search.solid.authing.cn-#1]
Solid.oauthing.cn refers to solid.authing.cn or do you intend to use the domain name oauthing.cn?

**Comment by mikeadams1** [comment]
I registered Search.solid.authing.cn as well as pods under the subjects in the attached graph however, cant access the Search.solid.authing.cn site as the password I created no longer works.

![image](https://user-images.githubusercontent.com/44804421/49804526-c4f56f00-fd20-11e8-9741-98eff1d7c4d7.png)

**Comment by mikeadams1** [comment]
I registered https://search.solid.authing.cn with the intent to interconnect, including but not limited to, the following pods:
https://news.solid.authing.cn
https://finaince.solid.authing.cn
https://politics.solid.authing.cn
https://weather.solid.autihng.cn
https://employment.solid.authing.cn
https://social.solid.authing.cn
https://shopping.solid.authing.cn
https://games.solid.authing.cn

**Comment by mikeadams1** [comment]
and; https://mail.solid.authing.cn

**Comment by leinue** [comment]
Your URL in readme seems to be wrong. Do you want to correct it?

**Comment by leinue** [comment]
I am very interested in you, I hope to communicate further, do you use instant messaging software?

**Comment by mikeadams1** [comment]
no IM APP

**Comment by mikeadams1** [comment]
do you have a preferred IM APP

**Comment by mikeadams1** [comment]
I did not see the URL in readme that was incorrect, sorry but, can you point that out for me...

**Comment by mikeadams1** [comment]
would love to work with you on this project as well

**Comment by mikeadams1** [comment]
I am quite new to Github and not sure of all the lingo, I think IM means instant message app, if thats what you meant, I dont currently use any but will if there is one you prefer to pm on.

**Comment by leinue** [comment]
You have written authing.cn as oauthing.cn ...

**Comment by leinue** [comment]
I am in China, we have time difference problems.Do you know WeChat, which is very popular in China.

**Comment by leinue** [comment]
#2 I Have created a pull request to fix the incorret url in readme.

**Comment by mikeadams1** [comment]
ok, I dont know where my brain was on the spelling part of all that but, got it fixed. also got wechat now, user mike adams id wxid_2aos43csa8yn22
